/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/heart.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/heart.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Heart_Full_cell.geometry} material={materials['Red.001']} position={[0.165, 0.193, 0.11]} />
      <mesh geometry={nodes.Heart_Full_cell001.geometry} material={materials['Red.001']} position={[-0.305, 0.17, -0.061]} />
      <mesh geometry={nodes.Heart_Full_cell002.geometry} material={materials['Red.001']} position={[0.102, -0.397, -0.06]} />
      <mesh geometry={nodes.Heart_Full_cell003.geometry} material={materials['Red.001']} position={[0.31, 0.176, -0.061]} />
      <mesh geometry={nodes.Heart_Full_cell004.geometry} material={materials['Red.001']} position={[0.033, -0.199, 0.188]} />
      <mesh geometry={nodes.Heart_Full_cell005.geometry} material={materials['Red.001']} position={[-0.375, 0.085, 0.11]} />
      <mesh geometry={nodes.Heart_Full_cell006.geometry} material={materials['Red.001']} position={[-0.194, 0.21, 0.05]} />
      <mesh geometry={nodes.Heart_Full_cell007.geometry} material={materials['Red.001']} position={[-0.308, 0.174, 0.061]} />
      <mesh geometry={nodes.Heart_Full_cell008.geometry} material={materials['Red.001']} position={[0.371, -0.141, -0.005]} />
      <mesh geometry={nodes.Heart_Full_cell009.geometry} material={materials['Red.001']} position={[0.137, 0.099, -0.18]} />
      <mesh geometry={nodes.Heart_Full_cell010.geometry} material={materials['Red.001']} position={[0.326, -0.127, 0.091]} />
      <mesh geometry={nodes.Heart_Full_cell011.geometry} material={materials['Red.001']} position={[0.384, -0.001, -0.067]} />
      <mesh geometry={nodes.Heart_Full_cell012.geometry} material={materials['Red.001']} position={[0.172, 0.189, -0.115]} />
      <mesh geometry={nodes.Heart_Full_cell013.geometry} material={materials['Red.001']} position={[-0.19, -0.002, 0.197]} />
      <mesh geometry={nodes.Heart_Full_cell014.geometry} material={materials['Red.001']} position={[-0.096, -0.161, 0.183]} />
      <mesh geometry={nodes.Heart_Full_cell015.geometry} material={materials['Red.001']} position={[0.219, 0.224, 0.023]} />
      <mesh geometry={nodes.Heart_Full_cell016.geometry} material={materials['Red.001']} position={[0.02, -0.049, 0.145]} />
      <mesh geometry={nodes.Heart_Full_cell017.geometry} material={materials['Red.001']} position={[-0.187, 0.013, -0.197]} />
      <mesh geometry={nodes.Heart_Full_cell018.geometry} material={materials['Red.001']} position={[0.162, 0.062, 0.198]} />
      <mesh geometry={nodes.Heart_Full_cell019.geometry} material={materials['Red.001']} position={[-0.002, -0.408, -0.082]} />
      <mesh geometry={nodes.Heart_Full_cell020.geometry} material={materials['Red.001']} position={[-0.366, 0.057, -0.13]} />
      <mesh geometry={nodes.Heart_Full_cell021.geometry} material={materials['Red.001']} position={[-0.337, -0.005, 0.151]} />
      <mesh geometry={nodes.Heart_Full_cell022.geometry} material={materials['Red.001']} position={[0.29, -0.11, -0.174]} />
      <mesh geometry={nodes.Heart_Full_cell023.geometry} material={materials['Red.001']} position={[0.358, 0.06, -0.138]} />
      <mesh geometry={nodes.Heart_Full_cell024.geometry} material={materials['Red.001']} position={[0.215, -0.107, 0.19]} />
      <mesh geometry={nodes.Heart_Full_cell025.geometry} material={materials['Red.001']} position={[-0.168, 0.173, -0.123]} />
      <mesh geometry={nodes.Heart_Full_cell026.geometry} material={materials['Red.001']} position={[0.269, 0.103, -0.161]} />
      <mesh geometry={nodes.Heart_Full_cell027.geometry} material={materials['Red.001']} position={[-0.098, 0.193, 0.002]} />
      <mesh geometry={nodes.Heart_Full_cell028.geometry} material={materials['Red.001']} position={[0, -0.435, 0.153]} />
      <mesh geometry={nodes.Heart_Full_cell029.geometry} material={materials['Red.001']} position={[-0.379, 0.097, 0.003]} />
      <mesh geometry={nodes.Heart_Full_cell030.geometry} material={materials['Red.001']} position={[-0.232, -0.15, 0.168]} />
      <mesh geometry={nodes.Heart_Full_cell031.geometry} material={materials['Red.001']} position={[-0.168, -0.275, 0.031]} />
      <mesh geometry={nodes.Heart_Full_cell032.geometry} material={materials['Red.001']} position={[0.316, -0.143, -0.074]} />
      <mesh geometry={nodes.Heart_Full_cell033.geometry} material={materials['Red.001']} position={[0.212, -0.252, 0.076]} />
      <mesh geometry={nodes.Heart_Full_cell034.geometry} material={materials['Red.001']} position={[-0.387, -0.077, -0.022]} />
      <mesh geometry={nodes.Heart_Full_cell035.geometry} material={materials['Red.001']} position={[0.154, -0.262, -0.091]} />
      <mesh geometry={nodes.Heart_Full_cell036.geometry} material={materials['Red.001']} position={[0.386, -0.004, 0.061]} />
      <mesh geometry={nodes.Heart_Full_cell037.geometry} material={materials['Red.001']} position={[-0.015, 0.134, -0.141]} />
      <mesh geometry={nodes.Heart_Full_cell038.geometry} material={materials['Red.001']} position={[-0.337, -0.125, 0.091]} />
      <mesh geometry={nodes.Heart_Full_cell039.geometry} material={materials['Red.001']} position={[0.316, -0.008, 0.146]} />
      <mesh geometry={nodes.Heart_Full_cell040.geometry} material={materials['Red.001']} position={[-0.244, -0.226, -0.108]} />
      <mesh geometry={nodes.Heart_Full_cell041.geometry} material={materials['Red.001']} position={[0.073, -0.372, 0.096]} />
      <mesh geometry={nodes.Heart_Full_cell042.geometry} material={materials['Red.001']} position={[-0.223, 0.127, 0.162]} />
      <mesh geometry={nodes.Heart_Full_cell043.geometry} material={materials['Red.001']} position={[0.288, 0.118, 0.147]} />
      <mesh geometry={nodes.Heart_Full_cell044.geometry} material={materials['Red.001']} position={[-0.085, -0.305, 0.197]} />
      <mesh geometry={nodes.Heart_Full_cell045.geometry} material={materials['Red.001']} position={[-0.034, 0.143, 0.14]} />
      <mesh geometry={nodes.Heart_Full_cell046.geometry} material={materials['Red.001']} position={[-0.005, -0.252, -0.079]} />
      <mesh geometry={nodes.Heart_Full_cell047.geometry} material={materials['Red.001']} position={[0.37, 0.119, 0.025]} />
      <mesh geometry={nodes.Heart_Full_cell048.geometry} material={materials['Red.001']} position={[-0.087, -0.402, -0.07]} />
      <mesh geometry={nodes.Heart_Full_cell049.geometry} material={materials['Red.001']} position={[-0.279, 0.118, -0.165]} />
      <mesh geometry={nodes.Heart_Full_cell050.geometry} material={materials['Red.001']} position={[-0.111, -0.233, -0.123]} />
      <mesh geometry={nodes.Heart_Full_cell051.geometry} material={materials['Red.001']} position={[-0.017, -0.04, -0.188]} />
      <mesh geometry={nodes.Heart_Full_cell052.geometry} material={materials['Red.001']} position={[-0.001, -0.471, -0.001]} />
      <mesh geometry={nodes.Heart_Full_cell053.geometry} material={materials['Red.001']} position={[-0.307, -0.197, 0.004]} />
      <mesh geometry={nodes.Heart_Full_cell054.geometry} material={materials['Red.001']} position={[0.219, -0.009, -0.192]} />
      <mesh geometry={nodes.Heart_Full_cell055.geometry} material={materials['Red.001']} position={[-0.063, -0.378, 0.072]} />
      <mesh geometry={nodes.Heart_Full_cell056.geometry} material={materials['Red.001']} position={[-0.287, -0.095, -0.171]} />
      <mesh geometry={nodes.Heart_Full_cell057.geometry} material={materials['Red.001']} position={[0.004, 0.036, 0]} />
      <mesh geometry={nodes.Heart_Full_cell058.geometry} material={materials['Red.001']} position={[0.134, -0.135, -0.13]} />
      <mesh geometry={nodes.Heart_Full_cell059.geometry} material={materials['Red.001']} position={[0.067, 0.24, -0.001]} />
      <mesh geometry={nodes.origin.geometry} material={materials['Red.001']} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
    </group>
  )
}

useGLTF.preload('/heart.glb')
