/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/heart.glb -o src/components/Heart.tsx -r public -k 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { useGLTF, useScroll } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import NodelURL from "/models/heart.glb";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    origin: THREE.Mesh;
    Heart_Full_cell: THREE.Mesh;
    Heart_Full_cell001: THREE.Mesh;
    Heart_Full_cell002: THREE.Mesh;
    Heart_Full_cell003: THREE.Mesh;
    Heart_Full_cell004: THREE.Mesh;
    Heart_Full_cell005: THREE.Mesh;
    Heart_Full_cell006: THREE.Mesh;
    Heart_Full_cell007: THREE.Mesh;
    Heart_Full_cell008: THREE.Mesh;
    Heart_Full_cell009: THREE.Mesh;
    Heart_Full_cell010: THREE.Mesh;
    Heart_Full_cell011: THREE.Mesh;
    Heart_Full_cell012: THREE.Mesh;
    Heart_Full_cell013: THREE.Mesh;
    Heart_Full_cell014: THREE.Mesh;
    Heart_Full_cell015: THREE.Mesh;
    Heart_Full_cell016: THREE.Mesh;
    Heart_Full_cell017: THREE.Mesh;
    Heart_Full_cell018: THREE.Mesh;
    Heart_Full_cell019: THREE.Mesh;
    Heart_Full_cell020: THREE.Mesh;
    Heart_Full_cell021: THREE.Mesh;
    Heart_Full_cell022: THREE.Mesh;
    Heart_Full_cell023: THREE.Mesh;
    Heart_Full_cell024: THREE.Mesh;
    Heart_Full_cell025: THREE.Mesh;
    Heart_Full_cell026: THREE.Mesh;
    Heart_Full_cell027: THREE.Mesh;
    Heart_Full_cell028: THREE.Mesh;
    Heart_Full_cell029: THREE.Mesh;
    Heart_Full_cell030: THREE.Mesh;
    Heart_Full_cell031: THREE.Mesh;
    Heart_Full_cell032: THREE.Mesh;
    Heart_Full_cell033: THREE.Mesh;
    Heart_Full_cell034: THREE.Mesh;
    Heart_Full_cell035: THREE.Mesh;
    Heart_Full_cell036: THREE.Mesh;
    Heart_Full_cell037: THREE.Mesh;
    Heart_Full_cell038: THREE.Mesh;
    Heart_Full_cell039: THREE.Mesh;
    Heart_Full_cell040: THREE.Mesh;
    Heart_Full_cell041: THREE.Mesh;
    Heart_Full_cell042: THREE.Mesh;
    Heart_Full_cell043: THREE.Mesh;
    Heart_Full_cell044: THREE.Mesh;
    Heart_Full_cell045: THREE.Mesh;
    Heart_Full_cell046: THREE.Mesh;
    Heart_Full_cell047: THREE.Mesh;
    Heart_Full_cell048: THREE.Mesh;
    Heart_Full_cell049: THREE.Mesh;
    Heart_Full_cell050: THREE.Mesh;
    Heart_Full_cell051: THREE.Mesh;
    Heart_Full_cell052: THREE.Mesh;
    Heart_Full_cell053: THREE.Mesh;
    Heart_Full_cell054: THREE.Mesh;
    Heart_Full_cell055: THREE.Mesh;
    Heart_Full_cell056: THREE.Mesh;
    Heart_Full_cell057: THREE.Mesh;
    Heart_Full_cell058: THREE.Mesh;
    Heart_Full_cell059: THREE.Mesh;
  };
  materials: {
    ["Red.001"]: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<
  string,
  React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>
>;

export function Heart(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(NodelURL) as GLTFResult;

  const group = useRef<THREE.Group>(null);

  console.log("heart group: ", group.current);

  useEffect(() => {
    if (group && group?.current) {
      const groupWorldPosition = new THREE.Vector3();
      group.current.getWorldPosition(groupWorldPosition);

      group.current.children.forEach((mesh) => {
        mesh.originalPosition = mesh.position.clone();
        const meshWorldPosition = new THREE.Vector3();
        mesh.getWorldPosition(meshWorldPosition);

        mesh.directionVector = meshWorldPosition
          .clone()
          .sub(groupWorldPosition)
          .normalize();

        mesh.targetPosition = mesh.originalPosition
          .clone()
          .add(mesh.directionVector.clone().multiplyScalar(0.5));
      });
    }
  }, []);

  const scrollData = useScroll();

  useFrame(() => {
    if (group && group?.current) {
      group.current.children.forEach((mesh) => {
        if (scrollData.offset < 0.0001) {
          if (mesh.name === "origin") {
            mesh.visible = true;
          } else {
            mesh.visible = false;
          }
        } else {
          if (mesh.name === "origin") {
            mesh.visible = false;
          } else {
            mesh.visible = true;
          }
        }

        if (mesh.targetPosition) {
          mesh.position.x = THREE.MathUtils.lerp(
            mesh.originalPosition.x,
            mesh.targetPosition.x,
            scrollData.offset * 4
          );

          mesh.position.y = THREE.MathUtils.lerp(
            mesh.originalPosition.y,
            mesh.targetPosition.y,
            scrollData.offset * 4
          );

          mesh.position.z = THREE.MathUtils.lerp(
            mesh.originalPosition.z,
            mesh.targetPosition.z,
            scrollData.offset * 4
          );
        }
      });
    }
  });

  return (
    <group {...props} dispose={null} ref={group}>
      <mesh
        name="Heart_Full_cell"
        geometry={nodes.Heart_Full_cell.geometry}
        material={materials["Red.001"]}
        position={[0.165, 0.193, 0.11]}
      />
      <mesh
        name="Heart_Full_cell001"
        geometry={nodes.Heart_Full_cell001.geometry}
        material={materials["Red.001"]}
        position={[-0.305, 0.17, -0.061]}
      />
      <mesh
        name="Heart_Full_cell002"
        geometry={nodes.Heart_Full_cell002.geometry}
        material={materials["Red.001"]}
        position={[0.102, -0.397, -0.06]}
      />
      <mesh
        name="Heart_Full_cell003"
        geometry={nodes.Heart_Full_cell003.geometry}
        material={materials["Red.001"]}
        position={[0.31, 0.176, -0.061]}
      />
      <mesh
        name="Heart_Full_cell004"
        geometry={nodes.Heart_Full_cell004.geometry}
        material={materials["Red.001"]}
        position={[0.033, -0.199, 0.188]}
      />
      <mesh
        name="Heart_Full_cell005"
        geometry={nodes.Heart_Full_cell005.geometry}
        material={materials["Red.001"]}
        position={[-0.375, 0.085, 0.11]}
      />
      <mesh
        name="Heart_Full_cell006"
        geometry={nodes.Heart_Full_cell006.geometry}
        material={materials["Red.001"]}
        position={[-0.194, 0.21, 0.05]}
      />
      <mesh
        name="Heart_Full_cell007"
        geometry={nodes.Heart_Full_cell007.geometry}
        material={materials["Red.001"]}
        position={[-0.308, 0.174, 0.061]}
      />
      <mesh
        name="Heart_Full_cell008"
        geometry={nodes.Heart_Full_cell008.geometry}
        material={materials["Red.001"]}
        position={[0.371, -0.141, -0.005]}
      />
      <mesh
        name="Heart_Full_cell009"
        geometry={nodes.Heart_Full_cell009.geometry}
        material={materials["Red.001"]}
        position={[0.137, 0.099, -0.18]}
      />
      <mesh
        name="Heart_Full_cell010"
        geometry={nodes.Heart_Full_cell010.geometry}
        material={materials["Red.001"]}
        position={[0.326, -0.127, 0.091]}
      />
      <mesh
        name="Heart_Full_cell011"
        geometry={nodes.Heart_Full_cell011.geometry}
        material={materials["Red.001"]}
        position={[0.384, -0.001, -0.067]}
      />
      <mesh
        name="Heart_Full_cell012"
        geometry={nodes.Heart_Full_cell012.geometry}
        material={materials["Red.001"]}
        position={[0.172, 0.189, -0.115]}
      />
      <mesh
        name="Heart_Full_cell013"
        geometry={nodes.Heart_Full_cell013.geometry}
        material={materials["Red.001"]}
        position={[-0.19, -0.002, 0.197]}
      />
      <mesh
        name="Heart_Full_cell014"
        geometry={nodes.Heart_Full_cell014.geometry}
        material={materials["Red.001"]}
        position={[-0.096, -0.161, 0.183]}
      />
      <mesh
        name="Heart_Full_cell015"
        geometry={nodes.Heart_Full_cell015.geometry}
        material={materials["Red.001"]}
        position={[0.219, 0.224, 0.023]}
      />
      <mesh
        name="Heart_Full_cell016"
        geometry={nodes.Heart_Full_cell016.geometry}
        material={materials["Red.001"]}
        position={[0.02, -0.049, 0.145]}
      />
      <mesh
        name="Heart_Full_cell017"
        geometry={nodes.Heart_Full_cell017.geometry}
        material={materials["Red.001"]}
        position={[-0.187, 0.013, -0.197]}
      />
      <mesh
        name="Heart_Full_cell018"
        geometry={nodes.Heart_Full_cell018.geometry}
        material={materials["Red.001"]}
        position={[0.162, 0.062, 0.198]}
      />
      <mesh
        name="Heart_Full_cell019"
        geometry={nodes.Heart_Full_cell019.geometry}
        material={materials["Red.001"]}
        position={[-0.002, -0.408, -0.082]}
      />
      <mesh
        name="Heart_Full_cell020"
        geometry={nodes.Heart_Full_cell020.geometry}
        material={materials["Red.001"]}
        position={[-0.366, 0.057, -0.13]}
      />
      <mesh
        name="Heart_Full_cell021"
        geometry={nodes.Heart_Full_cell021.geometry}
        material={materials["Red.001"]}
        position={[-0.337, -0.005, 0.151]}
      />
      <mesh
        name="Heart_Full_cell022"
        geometry={nodes.Heart_Full_cell022.geometry}
        material={materials["Red.001"]}
        position={[0.29, -0.11, -0.174]}
      />
      <mesh
        name="Heart_Full_cell023"
        geometry={nodes.Heart_Full_cell023.geometry}
        material={materials["Red.001"]}
        position={[0.358, 0.06, -0.138]}
      />
      <mesh
        name="Heart_Full_cell024"
        geometry={nodes.Heart_Full_cell024.geometry}
        material={materials["Red.001"]}
        position={[0.215, -0.107, 0.19]}
      />
      <mesh
        name="Heart_Full_cell025"
        geometry={nodes.Heart_Full_cell025.geometry}
        material={materials["Red.001"]}
        position={[-0.168, 0.173, -0.123]}
      />
      <mesh
        name="Heart_Full_cell026"
        geometry={nodes.Heart_Full_cell026.geometry}
        material={materials["Red.001"]}
        position={[0.269, 0.103, -0.161]}
      />
      <mesh
        name="Heart_Full_cell027"
        geometry={nodes.Heart_Full_cell027.geometry}
        material={materials["Red.001"]}
        position={[-0.098, 0.193, 0.002]}
      />
      <mesh
        name="Heart_Full_cell028"
        geometry={nodes.Heart_Full_cell028.geometry}
        material={materials["Red.001"]}
        position={[0, -0.435, 0.153]}
      />
      <mesh
        name="Heart_Full_cell029"
        geometry={nodes.Heart_Full_cell029.geometry}
        material={materials["Red.001"]}
        position={[-0.379, 0.097, 0.003]}
      />
      <mesh
        name="Heart_Full_cell030"
        geometry={nodes.Heart_Full_cell030.geometry}
        material={materials["Red.001"]}
        position={[-0.232, -0.15, 0.168]}
      />
      <mesh
        name="Heart_Full_cell031"
        geometry={nodes.Heart_Full_cell031.geometry}
        material={materials["Red.001"]}
        position={[-0.168, -0.275, 0.031]}
      />
      <mesh
        name="Heart_Full_cell032"
        geometry={nodes.Heart_Full_cell032.geometry}
        material={materials["Red.001"]}
        position={[0.316, -0.143, -0.074]}
      />
      <mesh
        name="Heart_Full_cell033"
        geometry={nodes.Heart_Full_cell033.geometry}
        material={materials["Red.001"]}
        position={[0.212, -0.252, 0.076]}
      />
      <mesh
        name="Heart_Full_cell034"
        geometry={nodes.Heart_Full_cell034.geometry}
        material={materials["Red.001"]}
        position={[-0.387, -0.077, -0.022]}
      />
      <mesh
        name="Heart_Full_cell035"
        geometry={nodes.Heart_Full_cell035.geometry}
        material={materials["Red.001"]}
        position={[0.154, -0.262, -0.091]}
      />
      <mesh
        name="Heart_Full_cell036"
        geometry={nodes.Heart_Full_cell036.geometry}
        material={materials["Red.001"]}
        position={[0.386, -0.004, 0.061]}
      />
      <mesh
        name="Heart_Full_cell037"
        geometry={nodes.Heart_Full_cell037.geometry}
        material={materials["Red.001"]}
        position={[-0.015, 0.134, -0.141]}
      />
      <mesh
        name="Heart_Full_cell038"
        geometry={nodes.Heart_Full_cell038.geometry}
        material={materials["Red.001"]}
        position={[-0.337, -0.125, 0.091]}
      />
      <mesh
        name="Heart_Full_cell039"
        geometry={nodes.Heart_Full_cell039.geometry}
        material={materials["Red.001"]}
        position={[0.316, -0.008, 0.146]}
      />
      <mesh
        name="Heart_Full_cell040"
        geometry={nodes.Heart_Full_cell040.geometry}
        material={materials["Red.001"]}
        position={[-0.244, -0.226, -0.108]}
      />
      <mesh
        name="Heart_Full_cell041"
        geometry={nodes.Heart_Full_cell041.geometry}
        material={materials["Red.001"]}
        position={[0.073, -0.372, 0.096]}
      />
      <mesh
        name="Heart_Full_cell042"
        geometry={nodes.Heart_Full_cell042.geometry}
        material={materials["Red.001"]}
        position={[-0.223, 0.127, 0.162]}
      />
      <mesh
        name="Heart_Full_cell043"
        geometry={nodes.Heart_Full_cell043.geometry}
        material={materials["Red.001"]}
        position={[0.288, 0.118, 0.147]}
      />
      <mesh
        name="Heart_Full_cell044"
        geometry={nodes.Heart_Full_cell044.geometry}
        material={materials["Red.001"]}
        position={[-0.085, -0.305, 0.197]}
      />
      <mesh
        name="Heart_Full_cell045"
        geometry={nodes.Heart_Full_cell045.geometry}
        material={materials["Red.001"]}
        position={[-0.034, 0.143, 0.14]}
      />
      <mesh
        name="Heart_Full_cell046"
        geometry={nodes.Heart_Full_cell046.geometry}
        material={materials["Red.001"]}
        position={[-0.005, -0.252, -0.079]}
      />
      <mesh
        name="Heart_Full_cell047"
        geometry={nodes.Heart_Full_cell047.geometry}
        material={materials["Red.001"]}
        position={[0.37, 0.119, 0.025]}
      />
      <mesh
        name="Heart_Full_cell048"
        geometry={nodes.Heart_Full_cell048.geometry}
        material={materials["Red.001"]}
        position={[-0.087, -0.402, -0.07]}
      />
      <mesh
        name="Heart_Full_cell049"
        geometry={nodes.Heart_Full_cell049.geometry}
        material={materials["Red.001"]}
        position={[-0.279, 0.118, -0.165]}
      />
      <mesh
        name="Heart_Full_cell050"
        geometry={nodes.Heart_Full_cell050.geometry}
        material={materials["Red.001"]}
        position={[-0.111, -0.233, -0.123]}
      />
      <mesh
        name="Heart_Full_cell051"
        geometry={nodes.Heart_Full_cell051.geometry}
        material={materials["Red.001"]}
        position={[-0.017, -0.04, -0.188]}
      />
      <mesh
        name="Heart_Full_cell052"
        geometry={nodes.Heart_Full_cell052.geometry}
        material={materials["Red.001"]}
        position={[-0.001, -0.471, -0.001]}
      />
      <mesh
        name="Heart_Full_cell053"
        geometry={nodes.Heart_Full_cell053.geometry}
        material={materials["Red.001"]}
        position={[-0.307, -0.197, 0.004]}
      />
      <mesh
        name="Heart_Full_cell054"
        geometry={nodes.Heart_Full_cell054.geometry}
        material={materials["Red.001"]}
        position={[0.219, -0.009, -0.192]}
      />
      <mesh
        name="Heart_Full_cell055"
        geometry={nodes.Heart_Full_cell055.geometry}
        material={materials["Red.001"]}
        position={[-0.063, -0.378, 0.072]}
      />
      <mesh
        name="Heart_Full_cell056"
        geometry={nodes.Heart_Full_cell056.geometry}
        material={materials["Red.001"]}
        position={[-0.287, -0.095, -0.171]}
      />
      <mesh
        name="Heart_Full_cell057"
        geometry={nodes.Heart_Full_cell057.geometry}
        material={materials["Red.001"]}
        position={[0.004, 0.036, 0]}
      />
      <mesh
        name="Heart_Full_cell058"
        geometry={nodes.Heart_Full_cell058.geometry}
        material={materials["Red.001"]}
        position={[0.134, -0.135, -0.13]}
      />
      <mesh
        name="Heart_Full_cell059"
        geometry={nodes.Heart_Full_cell059.geometry}
        material={materials["Red.001"]}
        position={[0.067, 0.24, -0.001]}
      />
      <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials["Red.001"]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload(NodelURL);
