/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/dude-modif.glb -o src/components/Dude.tsx -r public -k 
*/

import * as THREE from "three";
import React, { useEffect, useRef } from "react";
import { Html, useGLTF, useScroll } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import NodelURL from "/models/dude-modif.glb";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    origin: THREE.Mesh;
    Plane007_cell: THREE.Mesh;
    Plane007_cell001: THREE.Mesh;
    Plane007_cell002: THREE.Mesh;
    Plane007_cell004: THREE.Mesh;
    Plane007_cell005: THREE.Mesh;
    Plane007_cell006: THREE.Mesh;
    Plane007_cell007: THREE.Mesh;
    Plane007_cell008: THREE.Mesh;
    Plane007_cell009: THREE.Mesh;
    Plane007_cell010: THREE.Mesh;
    Plane007_cell011: THREE.Mesh;
    Plane007_cell012: THREE.Mesh;
    Plane007_cell013: THREE.Mesh;
    Plane007_cell014: THREE.Mesh;
    Plane007_cell015: THREE.Mesh;
    Plane007_cell016: THREE.Mesh;
    Plane007_cell017: THREE.Mesh;
    Plane007_cell018: THREE.Mesh;
    Plane007_cell019: THREE.Mesh;
    Plane007_cell020: THREE.Mesh;
    Plane007_cell021: THREE.Mesh;
    Plane007_cell022: THREE.Mesh;
    Plane007_cell023: THREE.Mesh;
    Plane007_cell024: THREE.Mesh;
    Plane007_cell025: THREE.Mesh;
    Plane007_cell026: THREE.Mesh;
    Plane007_cell027: THREE.Mesh;
    Plane007_cell028: THREE.Mesh;
    Plane007_cell029: THREE.Mesh;
    Plane007_cell030: THREE.Mesh;
    Plane007_cell032: THREE.Mesh;
    Plane007_cell033: THREE.Mesh;
    Plane007_cell035: THREE.Mesh;
    Plane007_cell036: THREE.Mesh;
    Plane007_cell037: THREE.Mesh;
    Plane007_cell038: THREE.Mesh;
    Plane007_cell039: THREE.Mesh;
    Plane007_cell040: THREE.Mesh;
    Plane007_cell041: THREE.Mesh;
    Plane007_cell042: THREE.Mesh;
    Plane007_cell043: THREE.Mesh;
    Plane007_cell044: THREE.Mesh;
    Plane007_cell045: THREE.Mesh;
    Plane007_cell046: THREE.Mesh;
    Plane007_cell047: THREE.Mesh;
    Plane007_cell048: THREE.Mesh;
    Plane007_cell049: THREE.Mesh;
    Plane007_cell050: THREE.Mesh;
    Plane007_cell051: THREE.Mesh;
    Plane007_cell052: THREE.Mesh;
    Plane007_cell053: THREE.Mesh;
    Plane007_cell057: THREE.Mesh;
    Plane007_cell058: THREE.Mesh;
    Plane007_cell059: THREE.Mesh;
    Plane007_cell060: THREE.Mesh;
    Plane007_cell061: THREE.Mesh;
    Plane007_cell062: THREE.Mesh;
    Plane007_cell063: THREE.Mesh;
    Plane007_cell064: THREE.Mesh;
    Plane007_cell065: THREE.Mesh;
    Plane007_cell066: THREE.Mesh;
    Plane007_cell067: THREE.Mesh;
    Plane007_cell068: THREE.Mesh;
    Plane007_cell069: THREE.Mesh;
    Plane007_cell070: THREE.Mesh;
    Plane007_cell071: THREE.Mesh;
    Plane007_cell072: THREE.Mesh;
    Plane007_cell073: THREE.Mesh;
    Plane007_cell074: THREE.Mesh;
    Plane007_cell075: THREE.Mesh;
    Plane007_cell076: THREE.Mesh;
    Plane007_cell077: THREE.Mesh;
    Plane007_cell078: THREE.Mesh;
    Plane007_cell079: THREE.Mesh;
    Plane007_cell080: THREE.Mesh;
    Plane007_cell081: THREE.Mesh;
    Plane007_cell082: THREE.Mesh;
    Plane007_cell083: THREE.Mesh;
    Plane007_cell084: THREE.Mesh;
    Plane007_cell085: THREE.Mesh;
    Plane007_cell086: THREE.Mesh;
    Plane007_cell087: THREE.Mesh;
    Plane007_cell088: THREE.Mesh;
    Plane007_cell089: THREE.Mesh;
    Plane007_cell090: THREE.Mesh;
    Plane007_cell092: THREE.Mesh;
    Plane007_cell093: THREE.Mesh;
    Plane007_cell003: THREE.Mesh;
    Plane007_cell055: THREE.Mesh;
    Plane007_cell091: THREE.Mesh;
    Plane007_cell095: THREE.Mesh;
  };
  materials: {
    DefaultMaterial: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

type ContextType = Record<string, React.ForwardRefExoticComponent<JSX.IntrinsicElements["mesh"]>>;

export function Dude(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(NodelURL) as GLTFResult;
  const group = useRef<THREE.Group>(null);

  console.log("dude group: ", group.current);

  useEffect(() => {
    if (group && group?.current) {
      const groupWorldPosition = new THREE.Vector3();
      group.current.getWorldPosition(groupWorldPosition);

      group.current.children.forEach((mesh) => {
        mesh.originalPosition = mesh.position.clone();
        const meshWorldPosition = new THREE.Vector3();
        mesh.getWorldPosition(meshWorldPosition);

        mesh.directionVector = meshWorldPosition.clone().sub(groupWorldPosition).normalize();

        mesh.targetPosition = mesh.originalPosition.clone().add(mesh.directionVector.clone().multiplyScalar(0.5));
      });
    }
  }, []);

  const scrollData = useScroll();

  // useFrame(() => {
  //   if (group && group?.current) {
  //     group.current.children.forEach((mesh) => {
  //       if (scrollData.offset < 0.0001) {
  //         if (mesh.name === "origin") {
  //           mesh.visible = true;
  //         } else {
  //           // mesh.visible = false;
  //         }
  //       } else {
  //         if (mesh.name === "origin") {
  //           // mesh.visible = false;
  //         } else {
  //           mesh.visible = true;
  //         }
  //       }

  //       if (mesh.targetPosition) {
  //         mesh.position.x = THREE.MathUtils.lerp(
  //           mesh.originalPosition.x,
  //           mesh.targetPosition.x,
  //           scrollData.offset * 2
  //         );

  //         mesh.position.y = THREE.MathUtils.lerp(
  //           mesh.originalPosition.y,
  //           mesh.targetPosition.y,
  //           scrollData.offset * 2
  //         );

  //         mesh.position.z = THREE.MathUtils.lerp(
  //           mesh.originalPosition.z,
  //           mesh.targetPosition.z,
  //           scrollData.offset
  //         );
  //       }
  //     });
  //   }
  // });

  return (
    <group {...props} dispose={null} position={[0, -2, 0]} ref={group}>
      {/* <Html style={{ position: "fixed" }}>FIXED HTML</Html> */}
      <mesh name="Plane007_cell" geometry={nodes.Plane007_cell.geometry} material={materials.DefaultMaterial} position={[-0.087, 0.711, 0.015]} />
      <mesh
        name="Plane007_cell001"
        geometry={nodes.Plane007_cell001.geometry}
        material={materials.DefaultMaterial}
        position={[0.082, 1.266, 0.006]}
      />
      <mesh
        name="Plane007_cell002"
        geometry={nodes.Plane007_cell002.geometry}
        material={materials.DefaultMaterial}
        position={[0.122, 0.628, 0.057]}
      />
      <mesh
        name="Plane007_cell004"
        geometry={nodes.Plane007_cell004.geometry}
        material={materials.DefaultMaterial}
        position={[0.028, 1.404, 0.182]}
      />
      <mesh
        name="Plane007_cell005"
        geometry={nodes.Plane007_cell005.geometry}
        material={materials.DefaultMaterial}
        position={[0.455, 1.066, 0.122]}
      />
      <mesh
        name="Plane007_cell006"
        geometry={nodes.Plane007_cell006.geometry}
        material={materials.DefaultMaterial}
        position={[-0.119, 0.467, -0.017]}
      />
      <mesh name="Plane007_cell007" geometry={nodes.Plane007_cell007.geometry} material={materials.DefaultMaterial} position={[0.057, 1.88, 0.098]} />
      <mesh
        name="Plane007_cell008"
        geometry={nodes.Plane007_cell008.geometry}
        material={materials.DefaultMaterial}
        position={[0.066, 1.837, 0.119]}
      />
      <mesh
        name="Plane007_cell009"
        geometry={nodes.Plane007_cell009.geometry}
        material={materials.DefaultMaterial}
        position={[-0.182, 0.038, 0.08]}
      />
      <mesh
        name="Plane007_cell010"
        geometry={nodes.Plane007_cell010.geometry}
        material={materials.DefaultMaterial}
        position={[0.071, 1.037, 0.137]}
      />
      <mesh
        name="Plane007_cell011"
        geometry={nodes.Plane007_cell011.geometry}
        material={materials.DefaultMaterial}
        position={[-0.289, 1.288, 0.062]}
      />
      <mesh
        name="Plane007_cell012"
        geometry={nodes.Plane007_cell012.geometry}
        material={materials.DefaultMaterial}
        position={[-0.095, 1.573, 0.012]}
      />
      <mesh
        name="Plane007_cell013"
        geometry={nodes.Plane007_cell013.geometry}
        material={materials.DefaultMaterial}
        position={[0.169, 0.026, 0.133]}
      />
      <mesh name="Plane007_cell014" geometry={nodes.Plane007_cell014.geometry} material={materials.DefaultMaterial} position={[0.167, 0.032, 0.09]} />
      <mesh
        name="Plane007_cell015"
        geometry={nodes.Plane007_cell015.geometry}
        material={materials.DefaultMaterial}
        position={[0.038, 1.878, 0.067]}
      />
      <mesh
        name="Plane007_cell016"
        geometry={nodes.Plane007_cell016.geometry}
        material={materials.DefaultMaterial}
        position={[-0.497, 0.926, 0.251]}
      />
      <mesh
        name="Plane007_cell017"
        geometry={nodes.Plane007_cell017.geometry}
        material={materials.DefaultMaterial}
        position={[-0.239, 1.438, 0.008]}
      />
      <mesh
        name="Plane007_cell018"
        geometry={nodes.Plane007_cell018.geometry}
        material={materials.DefaultMaterial}
        position={[0.071, 1.464, 0.148]}
      />
      <mesh
        name="Plane007_cell019"
        geometry={nodes.Plane007_cell019.geometry}
        material={materials.DefaultMaterial}
        position={[0.023, 1.624, 0.017]}
      />
      <mesh
        name="Plane007_cell020"
        geometry={nodes.Plane007_cell020.geometry}
        material={materials.DefaultMaterial}
        position={[0.066, 1.633, 0.069]}
      />
      <mesh
        name="Plane007_cell021"
        geometry={nodes.Plane007_cell021.geometry}
        material={materials.DefaultMaterial}
        position={[-0.199, 1.512, 0.059]}
      />
      <mesh name="Plane007_cell022" geometry={nodes.Plane007_cell022.geometry} material={materials.DefaultMaterial} position={[0.16, 0.5, 0.012]} />
      <mesh
        name="Plane007_cell023"
        geometry={nodes.Plane007_cell023.geometry}
        material={materials.DefaultMaterial}
        position={[-0.007, 1.832, 0.156]}
      />
      <mesh
        name="Plane007_cell024"
        geometry={nodes.Plane007_cell024.geometry}
        material={materials.DefaultMaterial}
        position={[-0.507, 0.952, 0.238]}
      />
      <mesh
        name="Plane007_cell025"
        geometry={nodes.Plane007_cell025.geometry}
        material={materials.DefaultMaterial}
        position={[-0.004, 1.794, 0.011]}
      />
      <mesh name="Plane007_cell026" geometry={nodes.Plane007_cell026.geometry} material={materials.DefaultMaterial} position={[0.243, 1.34, 0.058]} />
      <mesh
        name="Plane007_cell027"
        geometry={nodes.Plane007_cell027.geometry}
        material={materials.DefaultMaterial}
        position={[-0.349, 1.204, 0.061]}
      />
      <mesh
        name="Plane007_cell028"
        geometry={nodes.Plane007_cell028.geometry}
        material={materials.DefaultMaterial}
        position={[-0.037, 1.662, 0.053]}
      />
      <mesh
        name="Plane007_cell029"
        geometry={nodes.Plane007_cell029.geometry}
        material={materials.DefaultMaterial}
        position={[0.104, 0.885, 0.077]}
      />
      <mesh
        name="Plane007_cell030"
        geometry={nodes.Plane007_cell030.geometry}
        material={materials.DefaultMaterial}
        position={[0.469, 1.034, 0.243]}
      />
      <mesh
        name="Plane007_cell032"
        geometry={nodes.Plane007_cell032.geometry}
        material={materials.DefaultMaterial}
        position={[0.047, 1.723, 0.121]}
      />
      <mesh
        name="Plane007_cell033"
        geometry={nodes.Plane007_cell033.geometry}
        material={materials.DefaultMaterial}
        position={[-0.147, 0.752, 0.043]}
      />
      <mesh
        name="Plane007_cell035"
        geometry={nodes.Plane007_cell035.geometry}
        material={materials.DefaultMaterial}
        position={[0.128, 0.53, -0.029]}
      />
      <mesh
        name="Plane007_cell036"
        geometry={nodes.Plane007_cell036.geometry}
        material={materials.DefaultMaterial}
        position={[-0.014, 1.705, 0.136]}
      />
      <mesh
        name="Plane007_cell037"
        geometry={nodes.Plane007_cell037.geometry}
        material={materials.DefaultMaterial}
        position={[-0.11, 1.106, 0.125]}
      />
      <mesh
        name="Plane007_cell038"
        geometry={nodes.Plane007_cell038.geometry}
        material={materials.DefaultMaterial}
        position={[-0.103, 0.892, 0.058]}
      />
      <mesh name="Plane007_cell039" geometry={nodes.Plane007_cell039.geometry} material={materials.DefaultMaterial} position={[-0.46, 1.051, 0.21]} />
      <mesh
        name="Plane007_cell040"
        geometry={nodes.Plane007_cell040.geometry}
        material={materials.DefaultMaterial}
        position={[0.513, 0.924, 0.235]}
      />
      <mesh
        name="Plane007_cell041"
        geometry={nodes.Plane007_cell041.geometry}
        material={materials.DefaultMaterial}
        position={[-0.484, 1.026, 0.187]}
      />
      <mesh name="Plane007_cell042" geometry={nodes.Plane007_cell042.geometry} material={materials.DefaultMaterial} position={[0.1, 1.177, 0.117]} />
      <mesh
        name="Plane007_cell043"
        geometry={nodes.Plane007_cell043.geometry}
        material={materials.DefaultMaterial}
        position={[0.16, 0.332, -0.017]}
      />
      <mesh
        name="Plane007_cell044"
        geometry={nodes.Plane007_cell044.geometry}
        material={materials.DefaultMaterial}
        position={[-0.117, 1.291, 0.109]}
      />
      <mesh
        name="Plane007_cell045"
        geometry={nodes.Plane007_cell045.geometry}
        material={materials.DefaultMaterial}
        position={[-0.452, 1.017, 0.256]}
      />
      <mesh
        name="Plane007_cell046"
        geometry={nodes.Plane007_cell046.geometry}
        material={materials.DefaultMaterial}
        position={[-0.135, 0.042, 0.01]}
      />
      <mesh
        name="Plane007_cell047"
        geometry={nodes.Plane007_cell047.geometry}
        material={materials.DefaultMaterial}
        position={[-0.461, 1.055, 0.204]}
      />
      <mesh
        name="Plane007_cell048"
        geometry={nodes.Plane007_cell048.geometry}
        material={materials.DefaultMaterial}
        position={[0.509, 0.964, 0.209]}
      />
      <mesh
        name="Plane007_cell049"
        geometry={nodes.Plane007_cell049.geometry}
        material={materials.DefaultMaterial}
        position={[0.506, 0.967, 0.219]}
      />
      <mesh
        name="Plane007_cell050"
        geometry={nodes.Plane007_cell050.geometry}
        material={materials.DefaultMaterial}
        position={[-0.43, 1.093, 0.134]}
      />
      <mesh
        name="Plane007_cell051"
        geometry={nodes.Plane007_cell051.geometry}
        material={materials.DefaultMaterial}
        position={[0.059, 1.815, 0.038]}
      />
      <mesh name="Plane007_cell052" geometry={nodes.Plane007_cell052.geometry} material={materials.DefaultMaterial} position={[0.501, 1.008, 0.16]} />
      <mesh
        name="Plane007_cell053"
        geometry={nodes.Plane007_cell053.geometry}
        material={materials.DefaultMaterial}
        position={[-0.499, 0.972, 0.195]}
      />
      <mesh name="Plane007_cell057" geometry={nodes.Plane007_cell057.geometry} material={materials.DefaultMaterial} position={[0.028, 1.709, 0.04]} />
      <mesh
        name="Plane007_cell058"
        geometry={nodes.Plane007_cell058.geometry}
        material={materials.DefaultMaterial}
        position={[-0.178, 1.371, 0.021]}
      />
      <mesh
        name="Plane007_cell059"
        geometry={nodes.Plane007_cell059.geometry}
        material={materials.DefaultMaterial}
        position={[0.292, 1.283, 0.029]}
      />
      <mesh
        name="Plane007_cell060"
        geometry={nodes.Plane007_cell060.geometry}
        material={materials.DefaultMaterial}
        position={[0.121, 0.82, -0.004]}
      />
      <mesh name="Plane007_cell061" geometry={nodes.Plane007_cell061.geometry} material={materials.DefaultMaterial} position={[0.47, 1.05, 0.211]} />
      <mesh
        name="Plane007_cell062"
        geometry={nodes.Plane007_cell062.geometry}
        material={materials.DefaultMaterial}
        position={[0.04, 1.468, -0.041]}
      />
      <mesh
        name="Plane007_cell063"
        geometry={nodes.Plane007_cell063.geometry}
        material={materials.DefaultMaterial}
        position={[-0.11, 1.028, -0.013]}
      />
      <mesh
        name="Plane007_cell064"
        geometry={nodes.Plane007_cell064.geometry}
        material={materials.DefaultMaterial}
        position={[-0.056, 1.279, -0.005]}
      />
      <mesh name="Plane007_cell065" geometry={nodes.Plane007_cell065.geometry} material={materials.DefaultMaterial} position={[-0.142, 0.06, 0.08]} />
      <mesh
        name="Plane007_cell066"
        geometry={nodes.Plane007_cell066.geometry}
        material={materials.DefaultMaterial}
        position={[-0.131, 1.438, -0.031]}
      />
      <mesh
        name="Plane007_cell067"
        geometry={nodes.Plane007_cell067.geometry}
        material={materials.DefaultMaterial}
        position={[-0.302, 1.309, 0.022]}
      />
      <mesh
        name="Plane007_cell068"
        geometry={nodes.Plane007_cell068.geometry}
        material={materials.DefaultMaterial}
        position={[-0.173, 0.01, 0.053]}
      />
      <mesh
        name="Plane007_cell069"
        geometry={nodes.Plane007_cell069.geometry}
        material={materials.DefaultMaterial}
        position={[0.165, 0.043, 0.006]}
      />
      <mesh
        name="Plane007_cell070"
        geometry={nodes.Plane007_cell070.geometry}
        material={materials.DefaultMaterial}
        position={[-0.03, 1.865, 0.071]}
      />
      <mesh
        name="Plane007_cell071"
        geometry={nodes.Plane007_cell071.geometry}
        material={materials.DefaultMaterial}
        position={[0.112, 1.573, -0.004]}
      />
      <mesh
        name="Plane007_cell072"
        geometry={nodes.Plane007_cell072.geometry}
        material={materials.DefaultMaterial}
        position={[0.047, 1.061, -0.025]}
      />
      <mesh
        name="Plane007_cell073"
        geometry={nodes.Plane007_cell073.geometry}
        material={materials.DefaultMaterial}
        position={[-0.052, 1.766, 0.087]}
      />
      <mesh
        name="Plane007_cell074"
        geometry={nodes.Plane007_cell074.geometry}
        material={materials.DefaultMaterial}
        position={[0.336, 1.283, 0.059]}
      />
      <mesh name="Plane007_cell075" geometry={nodes.Plane007_cell075.geometry} material={materials.DefaultMaterial} position={[0.162, 0.14, 0.001]} />
      <mesh
        name="Plane007_cell076"
        geometry={nodes.Plane007_cell076.geometry}
        material={materials.DefaultMaterial}
        position={[-0.095, 1.178, 0.018]}
      />
      <mesh
        name="Plane007_cell077"
        geometry={nodes.Plane007_cell077.geometry}
        material={materials.DefaultMaterial}
        position={[-0.186, 1.523, -0.013]}
      />
      <mesh
        name="Plane007_cell078"
        geometry={nodes.Plane007_cell078.geometry}
        material={materials.DefaultMaterial}
        position={[0.053, 1.795, 0.113]}
      />
      <mesh
        name="Plane007_cell079"
        geometry={nodes.Plane007_cell079.geometry}
        material={materials.DefaultMaterial}
        position={[0.169, 1.541, 0.063]}
      />
      <mesh
        name="Plane007_cell080"
        geometry={nodes.Plane007_cell080.geometry}
        material={materials.DefaultMaterial}
        position={[-0.452, 1.017, 0.256]}
      />
      <mesh
        name="Plane007_cell081"
        geometry={nodes.Plane007_cell081.geometry}
        material={materials.DefaultMaterial}
        position={[-0.143, 0.582, 0.044]}
      />
      <mesh
        name="Plane007_cell082"
        geometry={nodes.Plane007_cell082.geometry}
        material={materials.DefaultMaterial}
        position={[0.201, 1.416, 0.032]}
      />
      <mesh
        name="Plane007_cell083"
        geometry={nodes.Plane007_cell083.geometry}
        material={materials.DefaultMaterial}
        position={[-0.021, 1.336, 0.182]}
      />
      <mesh
        name="Plane007_cell084"
        geometry={nodes.Plane007_cell084.geometry}
        material={materials.DefaultMaterial}
        position={[-0.504, 0.953, 0.198]}
      />
      <mesh
        name="Plane007_cell085"
        geometry={nodes.Plane007_cell085.geometry}
        material={materials.DefaultMaterial}
        position={[-0.045, 1.534, 0.142]}
      />
      <mesh
        name="Plane007_cell086"
        geometry={nodes.Plane007_cell086.geometry}
        material={materials.DefaultMaterial}
        position={[0.461, 1.017, 0.257]}
      />
      <mesh name="Plane007_cell087" geometry={nodes.Plane007_cell087.geometry} material={materials.DefaultMaterial} position={[0.067, 1.55, 0.111]} />
      <mesh
        name="Plane007_cell088"
        geometry={nodes.Plane007_cell088.geometry}
        material={materials.DefaultMaterial}
        position={[-0.158, 0.168, -0.014]}
      />
      <mesh name="Plane007_cell089" geometry={nodes.Plane007_cell089.geometry} material={materials.DefaultMaterial} position={[0.36, 1.196, 0.074]} />
      <mesh
        name="Plane007_cell090"
        geometry={nodes.Plane007_cell090.geometry}
        material={materials.DefaultMaterial}
        position={[-0.163, 0.417, 0.002]}
      />
      <mesh
        name="Plane007_cell092"
        geometry={nodes.Plane007_cell092.geometry}
        material={materials.DefaultMaterial}
        position={[-0.178, 1.425, 0.099]}
      />
      <mesh
        name="Plane007_cell093"
        geometry={nodes.Plane007_cell093.geometry}
        material={materials.DefaultMaterial}
        position={[0.448, 1.085, 0.147]}
      />
      <mesh name="Plane007_cell003" geometry={nodes.Plane007_cell003.geometry} material={materials.DefaultMaterial} position={[0.058, 0.703, 0.03]} />
      <mesh
        name="Plane007_cell055"
        geometry={nodes.Plane007_cell055.geometry}
        material={materials.DefaultMaterial}
        position={[0.135, 1.345, 0.092]}
      />
      <mesh name="Plane007_cell091" geometry={nodes.Plane007_cell091.geometry} material={materials.DefaultMaterial} position={[0.5, 1.007, 0.205]} />
      <mesh
        name="Plane007_cell095"
        geometry={nodes.Plane007_cell095.geometry}
        material={materials.DefaultMaterial}
        position={[-0.505, 0.979, 0.158]}
      />
      {/* <mesh
        name="origin"
        geometry={nodes.origin.geometry}
        material={materials.DefaultMaterial}
        scale={3.721}
        position={[0, 1.5, 0.2]}
      /> */}
      {/* <group name="RootNode" position={[-6.393, 0, 0]}>
        <mesh
          name="origin"
          geometry={nodes.origin.geometry}
          material={materials.DefaultMaterial}
          position={[6.397, 1.489, 0.198]}
          scale={3.721}
        />
      </group> */}
    </group>
  );
}

useGLTF.preload(NodelURL);
